-- Generated by scripts/build-vehicle-master.mjs at 2026-05-30T00:42:37.985Z
-- Run this file first in Supabase SQL Editor.

create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";

do $$
declare
  backup_table text := 'vehicle_master_backup_' || to_char(now(), 'YYYYMMDD_HH24MISS');
begin
  if to_regclass('public.vehicle_master') is not null then
    execute format('create table public.%I as table public.vehicle_master', backup_table);
  end if;
end $$;

drop table if exists public.vehicle_master;

create table public.vehicle_master (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'carmanager',
  source_maker_no integer,
  source_model_no integer,
  source_model_detail_no integer,
  manufacturer text not null,
  model text not null,
  model_detail text not null,
  aliases text[] not null default '{}'::text[],
  search_text text not null,
  search_text_normalized text not null,
  country text,
  maker_code text,
  model_code text,
  model_detail_code text,
  kind_code text,
  kind_sub_code text,
  sort_order integer,
  active_car_count integer,
  source_created_at_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicle_master_source_detail_unique unique (source, source_model_detail_no),
  constraint vehicle_master_name_unique unique (manufacturer, model, model_detail)
);
