-- Generated by scripts/build-vehicle-master.mjs at 2026-05-30T00:42:37.985Z
-- Run this file after all insert parts.

create index vehicle_master_manufacturer_idx
  on public.vehicle_master (manufacturer);

create index vehicle_master_model_idx
  on public.vehicle_master (model);

create index vehicle_master_model_detail_idx
  on public.vehicle_master (model_detail);

create index vehicle_master_aliases_gin_idx
  on public.vehicle_master using gin (aliases);

create index vehicle_master_search_text_trgm_idx
  on public.vehicle_master using gin (search_text gin_trgm_ops);

create index vehicle_master_search_text_normalized_trgm_idx
  on public.vehicle_master using gin (search_text_normalized gin_trgm_ops);

alter table public.vehicle_master enable row level security;

drop policy if exists "Public read vehicle master" on public.vehicle_master;
create policy "Public read vehicle master"
  on public.vehicle_master for select
  using (true);

-- Validation:
-- select count(*) as row_count,
--        count(distinct manufacturer) as manufacturer_count,
--        count(distinct manufacturer || '|' || model) as model_count,
--        count(distinct manufacturer || '|' || model || '|' || model_detail) as model_detail_count
-- from public.vehicle_master;
